name: shelfsdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  mime: ^1.0.5
  socket_io_client: ^3.0.0-beta.2

dev_dependencies:
  freezed: ^2.5.2
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  source_gen: ^1.5.0
